/**
 * Serves the Firebase Messaging service worker at /firebase-messaging-sw.js
 * with Firebase config injected from server-side env vars at request time.
 *
 * Firebase Web SDK requires the service worker to be accessible at this exact
 * path (convention). Serving it via a route handler lets us inject NEXT_PUBLIC_*
 * env vars without hardcoding them into a static file.
 *
 * Note: these values are all PUBLIC by design (served to every browser).
 */
import { NextResponse } from 'next/server';

export const dynamic = 'force-static';

export function GET(): NextResponse {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? '',
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? '',
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? '',
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? '',
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? '',
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? '',
  };

  const sw = `// Firebase Cloud Messaging service worker (auto-generated by /firebase-messaging-sw.js route)
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

// Take control of pages immediately so getToken() can use this registration
self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});

// Background message handler — shows native notification when page is closed/backgrounded
messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || payload.data?.title || 'Notifio';
  const options = {
    body: payload.notification?.body || payload.data?.body || '',
    icon: '/icon-192.png',
    badge: '/icon-96.png',
    tag: payload.data?.eventId || undefined,
    data: payload.data || {},
  };
  self.registration.showNotification(title, options);
});

// Notification click handler — opens the app / event detail page
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const eventId = event.notification.data?.eventId;
  const url = eventId ? \`/dashboard?event=\${eventId}\` : '/dashboard';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
`;

  return new NextResponse(sw, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Service-Worker-Allowed': '/',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
